name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubunto-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "fnc-liturgy" #Must be unique in Heroku
                heroku_email: "aar241@gmail.com"